<%@ Control Language="C#" ClassName="test" Inherits="Sage.Platform.WebPortal.SmartParts.EntityBoundSmartPartInfoProvider" %>
<%@ Register Assembly="Sage.SalesLogix.Client.GroupBuilder" Namespace="Sage.SalesLogix.Client.GroupBuilder" TagPrefix="SalesLogix" %>
<%@ Register Assembly="Sage.SalesLogix.Web.Controls" Namespace="Sage.SalesLogix.Web.Controls.PickList" TagPrefix="SalesLogix" %>
<%@ Register Assembly="Sage.SalesLogix.Web.Controls" Namespace="Sage.SalesLogix.Web.Controls" TagPrefix="SalesLogix" %>
<%@ Register Assembly="Sage.SalesLogix.Web.Controls" Namespace="Sage.SalesLogix.Web.Controls.DependencyLookup" TagPrefix="SalesLogix" %>
<%@ Register Assembly="Sage.SalesLogix.Web.Controls" Namespace="Sage.SalesLogix.Web.Controls.Lookup" TagPrefix="SalesLogix" %>
<%@ Register Assembly="Sage.SalesLogix.Web.Controls" Namespace="Sage.SalesLogix.Web.Controls.Timeline" TagPrefix="SalesLogix" %>
<%@ Register Assembly="Sage.SalesLogix.HighLevelTypes" Namespace="Sage.SalesLogix.HighLevelTypes" TagPrefix="SalesLogix" %>
<%@ Register Assembly="Sage.Platform.WebPortal" Namespace="Sage.Platform.WebPortal.SmartParts" TagPrefix="SalesLogix" %>

<%//------------------------------------------------------------------------
//This file was generated by a tool.  Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
//------------------------------------------------------------------------ %>
  <SalesLogix:SlxGridView runat="server" ID="grdBranchSurveyors" GridLines="None"
AutoGenerateColumns="false" CellPadding="4" CssClass="datagrid" PagerStyle-CssClass="gridPager"
AlternatingRowStyle-CssClass="rowdk" RowStyle-CssClass="rowlt" SelectedRowStyle-CssClass="rowSelected" ShowEmptyTable="true" EnableViewState="false"
 ExpandableRows="True" ResizableColumns="True" >
<Columns>
   <asp:BoundField DataField="Surveyor.EmailAddress"
      HeaderText="<%$ resources: grdBranchSurveyors.0ad09273-efe8-44b2-9f54-d1811151e758.ColumnHeading %>"          >
      </asp:BoundField>
    <asp:BoundField DataField="Surveyor.FirstName"
      HeaderText="<%$ resources: grdBranchSurveyors.bca16671-0714-4f1a-9ce4-2a2e3a99d632.ColumnHeading %>"          >
      </asp:BoundField>
    <asp:BoundField DataField="Surveyor.LastName"
      HeaderText="<%$ resources: grdBranchSurveyors.ac83667c-fad0-4801-ab70-761711c54ee3.ColumnHeading %>"          >
      </asp:BoundField>
    <asp:BoundField DataField="Surveyor.MobileNo"
      HeaderText="<%$ resources: grdBranchSurveyors.84752cdc-02aa-43e0-930d-ff68bde2ae0e.ColumnHeading %>"          >
      </asp:BoundField>
 </Columns>
</SalesLogix:SlxGridView>

<script runat="server" type="text/C#">


</script>
 


 <SalesLogix:SmartPartToolsContainer runat="server" ID="test_RTools" ToolbarLocation="right">
  <SalesLogix:PageLink ID="btnEditForm" CssClass="adminEditFormButton" runat="server" LinkType="RelativePath" ToolTip="<%$ resources: Portal, EditForm_ToolTip %>" NavigateUrl="~/FormManager.aspx?entityid=test&modeid=Detail" ImageUrl="~/ImageResource.axd?scope=global&type=Global_Images&key=form_manager_16x16"></SalesLogix:PageLink>
 
 
 
 
 <SalesLogix:PageLink ID="lnktestHelp" runat="server" LinkType="HelpFileName" ToolTip="<%$ resources: Portal, Help_ToolTip %>" Target="MCWebHelp" NavigateUrl="test" ImageUrl="~/ImageResource.axd?scope=global&type=Global_Images&key=Help_16x16"></SalesLogix:PageLink>
 </SalesLogix:SmartPartToolsContainer>



<script runat="server" type="text/C#">
/// <summary>
/// Gets or sets the role security service.
/// </summary>
/// <value>The role security service.</value>
[Sage.Platform.Application.ServiceDependency]
public Sage.Platform.Security.IRoleSecurityService RoleSecurityService { get; set; }

public override Type EntityType
{
    get { return typeof(Sage.Entity.Interfaces.IBranch); }
}

 private Sage.Platform.WebPortal.Binding.WebEntityListBindingSource _dsBranchSurveyors;
public Sage.Platform.WebPortal.Binding.WebEntityListBindingSource dsBranchSurveyors
{ 
  get 
  {
    if (_dsBranchSurveyors == null)
    {
             _dsBranchSurveyors = new Sage.Platform.WebPortal.Binding.WebEntityListBindingSource(typeof(Sage.Entity.Interfaces.IBranchSurveyor), 
	    EntityType              ,"Surveyors", System.Reflection.MemberTypes.Property);
                   _dsBranchSurveyors.UseSmartQuery = true;
      	   	}
 	return _dsBranchSurveyors;
  }
}

void dsBranchSurveyors_OnCurrentEntitySet(object sender, EventArgs e) 
{
      if (Visible)
    { 
		if(BindingSource.Current != null)
		{
		
      
        dsBranchSurveyors.SourceObject = BindingSource.Current;
   		}
    }
   if (Visible)
   {   
      RegisterBindingsWithClient(dsBranchSurveyors);
   }
}

 



 

protected override void OnAddEntityBindings() {
       dsBranchSurveyors.Bindings.Add(new Sage.Platform.WebPortal.Binding.WebEntityListBinding("Surveyors", grdBranchSurveyors ));
   dsBranchSurveyors.BindFieldNames = new String[] { "Id","Surveyor.EmailAddress","Surveyor.FirstName","Surveyor.LastName","Surveyor.MobileNo" };
     
     BindingSource.OnCurrentEntitySet += new EventHandler(dsBranchSurveyors_OnCurrentEntitySet);
    
}
       

protected override void OnWireEventHandlers()
{
 base.OnWireEventHandlers();
 
}

protected override void OnFormBound()
{
if (!RoleSecurityService.HasAccess("Administration/Forms/View"))
{
btnEditForm.Visible = false;
}
if (dsBranchSurveyors.SourceObject == null) { dsBranchSurveyors.SourceObject = BindingSource.Current; }
if (dsBranchSurveyors.SourceObject == null) { RegisterBindingsWithClient(dsBranchSurveyors); }
dsBranchSurveyors.Bind();



}



public override Sage.Platform.Application.UI.ISmartPartInfo GetSmartPartInfo(Type smartPartInfoType)
{
    ToolsSmartPartInfo tinfo = new ToolsSmartPartInfo();
        if (BindingSource != null)
    {
        if (BindingSource.Current != null)
        {
            tinfo.Description = BindingSource.Current.ToString();
            tinfo.Title = BindingSource.Current.ToString();
        }
    }
    
    foreach (Control c in Controls)
    {
        SmartPartToolsContainer cont = c as SmartPartToolsContainer;
        if (cont != null)
        {
            switch (cont.ToolbarLocation)
            {
                case SmartPartToolsLocation.Right:
                    foreach (Control tool in cont.Controls)
                    {
                                            tinfo.RightTools.Add(tool);
                                        }
                    break;
                case SmartPartToolsLocation.Center:
                    foreach (Control tool in cont.Controls)
                    {
                        tinfo.CenterTools.Add(tool);
                    }
                    break;
                case SmartPartToolsLocation.Left:
                    foreach (Control tool in cont.Controls)
                    {
                        tinfo.LeftTools.Add(tool);
                    }
                    break;
            }
        }
    }

        return tinfo;
}

private Sage.Platform.Controls.IEntityForm _formAdapter;

public Sage.Platform.Controls.IEntityForm FormAdapter
{
    get { return _formAdapter ?? (_formAdapter = new testAdapter(this)); }
}

public class testAdapter : Sage.Platform.WebPortal.Adapters.EntityFormAdapter, Sage.Form.Interfaces.Itest
{
    public testAdapter(Sage.Platform.WebPortal.SmartParts.EntityBoundSmartPartInfoProvider smartPart)
        : base(smartPart) {}

    private Sage.Platform.Controls.IDataGridControl _grdBranchSurveyors;
    public  Sage.Platform.Controls.IDataGridControl grdBranchSurveyors
    {
        get { return FindControl(ref _grdBranchSurveyors, "grdBranchSurveyors"); }
    }
    private Sage.Platform.Controls.IDataSourceControl _dsBranchSurveyors;
    public  Sage.Platform.Controls.IDataSourceControl dsBranchSurveyors
    {
        get { return FindControl(ref _dsBranchSurveyors, "dsBranchSurveyors"); }
    }

}

</script>

<script type="text/javascript">
</script>
